version: '2'
services:
  mongo:
    image: mongo:3.4
  web:
    build: .
    ports:
     - "3000:3000"
    environment:
     - MONGODB_URI=mongodb://rizwan:rizwan@ds127883.mlab.com:27883/talenthome
    links:
     - mongo 
    depends_on: 
     - mongo 
    volumes:
     - .:/starter
     - /starter/node_modules
     